Added color by status code #29
phra/rustbuster pull request #50
Opened 2021-10-24 18:08 UTC by ChandanChainani

![image](https://user-images.githubusercontent.com/28807775/138706365-39975c6b-6f28-412e-ba3d-2fd3c9ac4706.png)

2021-10-25 12:08 UTC, phra commented
can you attach an example of the output result? thanks!

2021-10-25 13:42 UTC, ChandanChainani commented
@phra  I have attached the screenshot

Only added color in dir status code, didn't added the response size.

2021-10-26 23:21 UTC, phra requested changes
can you add `console` to to `Cargo.toml`?

2021-10-27 03:14 UTC, ChandanChainani commented
@phra Sorry i forgot to include the dependency added as mentioned.

2021-10-27 04:01 UTC, phra requested changes

2021-10-27 04:01 UTC, phra commented on src/dirbuster/mod.rs
> +        return style(code).magenta().to_string();
I think yellow makes more sense for 3xx

2021-10-27 04:01 UTC, phra commented on src/dirbuster/mod.rs
> +        return style(code).yellow().to_string();
Maybe orange better fits 4xx

2021-10-27 04:56 UTC, ChandanChainani commented
@phra updated 3xx and 4xx status color as mentioned

![image](https://user-images.githubusercontent.com/28807775/139002318-51652cf9-bc30-411c-83e4-78367a98ea69.png)

2021-10-27 11:13 UTC, phra approved these changes
LGTM

2021-10-27 11:13 UTC, merged